---

- name: Allow  ssh
  become: yes
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify: reload ufw

- name: Set default in
  command: "ufw default {{ufw_default_incoming}} incoming"
  become: yes

- name: Set default out
  command: "ufw default {{ufw_default_outgoing}} outgoing"
  become: yes

- name: Set default routed
  command: "ufw default {{ufw_default_routed}} routed"
  become: yes

- name: Enable ufw
  become: yes
  ufw:
    state: enabled